export interface StockDefinition {
  code: string;
  name: string;
  type: string;
  currency: string;
}

// In a real application, this would be fetched from a database or API.
// This list contains major Nikkei 225 components, popular US stocks, and ETFs.
export const POPULAR_ASSETS: StockDefinition[] = [
  // --- Japanese Stocks (Major) ---
  { code: '7203', name: 'トヨタ自動車 (TOYOTA)', type: 'Stock', currency: 'JPY' },
  { code: '6758', name: 'ソニーグループ (SONY)', type: 'Stock', currency: 'JPY' },
  { code: '9984', name: 'ソフトバンクグループ (SBG)', type: 'Stock', currency: 'JPY' },
  { code: '9434', name: 'ソフトバンク (SoftBank)', type: 'Stock', currency: 'JPY' },
  { code: '6861', name: 'キーエンス (KEYENCE)', type: 'Stock', currency: 'JPY' },
  { code: '8306', name: '三菱UFJフィナンシャルG (MUFG)', type: 'Stock', currency: 'JPY' },
  { code: '8316', name: '三井住友フィナンシャルG (SMFG)', type: 'Stock', currency: 'JPY' },
  { code: '8411', name: 'みずほフィナンシャルG (Mizuho)', type: 'Stock', currency: 'JPY' },
  { code: '9432', name: '日本電信電話 (NTT)', type: 'Stock', currency: 'JPY' },
  { code: '9433', name: 'KDDI', type: 'Stock', currency: 'JPY' },
  { code: '8035', name: '東京エレクトロン (TEL)', type: 'Stock', currency: 'JPY' },
  { code: '6098', name: 'リクルートホールディングス', type: 'Stock', currency: 'JPY' },
  { code: '4063', name: '信越化学工業', type: 'Stock', currency: 'JPY' },
  { code: '7974', name: '任天堂 (Nintendo)', type: 'Stock', currency: 'JPY' },
  { code: '8001', name: '伊藤忠商事', type: 'Stock', currency: 'JPY' },
  { code: '8058', name: '三菱商事', type: 'Stock', currency: 'JPY' },
  { code: '8031', name: '三井物産', type: 'Stock', currency: 'JPY' },
  { code: '8002', name: '丸紅', type: 'Stock', currency: 'JPY' },
  { code: '8053', name: '住友商事', type: 'Stock', currency: 'JPY' },
  { code: '9983', name: 'ファーストリテイリング (Uniqlo)', type: 'Stock', currency: 'JPY' },
  { code: '6954', name: 'ファナック (FANUC)', type: 'Stock', currency: 'JPY' },
  { code: '6594', name: 'ニデック (Nidec)', type: 'Stock', currency: 'JPY' },
  { code: '6981', name: '村田製作所', type: 'Stock', currency: 'JPY' },
  { code: '7741', name: 'HOYA', type: 'Stock', currency: 'JPY' },
  { code: '4502', name: '武田薬品工業', type: 'Stock', currency: 'JPY' },
  { code: '4503', name: 'アステラス製薬', type: 'Stock', currency: 'JPY' },
  { code: '4519', name: '中外製薬', type: 'Stock', currency: 'JPY' },
  { code: '4568', name: '第一三共', type: 'Stock', currency: 'JPY' },
  { code: '4543', name: 'テルモ', type: 'Stock', currency: 'JPY' },
  { code: '6367', name: 'ダイキン工業', type: 'Stock', currency: 'JPY' },
  { code: '6501', name: '日立製作所', type: 'Stock', currency: 'JPY' },
  { code: '6701', name: '日本電気 (NEC)', type: 'Stock', currency: 'JPY' },
  { code: '6702', name: '富士通', type: 'Stock', currency: 'JPY' },
  { code: '6752', name: 'パナソニックHD', type: 'Stock', currency: 'JPY' },
  { code: '7751', name: 'キヤノン', type: 'Stock', currency: 'JPY' },
  { code: '6902', name: 'デンソー', type: 'Stock', currency: 'JPY' },
  { code: '7267', name: '本田技研工業 (Honda)', type: 'Stock', currency: 'JPY' },
  { code: '7201', name: '日産自動車', type: 'Stock', currency: 'JPY' },
  { code: '7269', name: 'スズキ', type: 'Stock', currency: 'JPY' },
  { code: '5108', name: 'ブリヂストン', type: 'Stock', currency: 'JPY' },
  { code: '2914', name: '日本たばこ産業 (JT)', type: 'Stock', currency: 'JPY' },
  { code: '4661', name: 'オリエンタルランド (Disney)', type: 'Stock', currency: 'JPY' },
  { code: '4901', name: '富士フイルムHD', type: 'Stock', currency: 'JPY' },
  { code: '8801', name: '三井不動産', type: 'Stock', currency: 'JPY' },
  { code: '8802', name: '三菱地所', type: 'Stock', currency: 'JPY' },
  { code: '6273', name: 'SMC', type: 'Stock', currency: 'JPY' },
  { code: '9843', name: 'ニトリHD', type: 'Stock', currency: 'JPY' },
  { code: '3382', name: 'セブン＆アイHD', type: 'Stock', currency: 'JPY' },
  { code: '8267', name: 'イオン', type: 'Stock', currency: 'JPY' },
  { code: '8766', name: '東京海上HD', type: 'Stock', currency: 'JPY' },
  { code: '8725', name: 'MS&ADインシュアランス', type: 'Stock', currency: 'JPY' },
  { code: '8750', name: '第一生命HD', type: 'Stock', currency: 'JPY' },
  { code: '9020', name: '東日本旅客鉄道 (JR East)', type: 'Stock', currency: 'JPY' },
  { code: '9021', name: '西日本旅客鉄道 (JR West)', type: 'Stock', currency: 'JPY' },
  { code: '9022', name: '東海旅客鉄道 (JR Central)', type: 'Stock', currency: 'JPY' },
  { code: '9201', name: '日本航空 (JAL)', type: 'Stock', currency: 'JPY' },
  { code: '9202', name: 'ANAホールディングス', type: 'Stock', currency: 'JPY' },
  { code: '4385', name: 'メルカリ', type: 'Stock', currency: 'JPY' },
  { code: '4755', name: '楽天グループ', type: 'Stock', currency: 'JPY' },
  { code: '2502', name: 'アサヒグループHD', type: 'Stock', currency: 'JPY' },
  { code: '2503', name: 'キリンHD', type: 'Stock', currency: 'JPY' },
  { code: '2802', name: '味の素', type: 'Stock', currency: 'JPY' },

  // --- US Stocks (Major) ---
  { code: 'AAPL', name: 'Apple Inc.', type: 'Stock', currency: 'USD' },
  { code: 'MSFT', name: 'Microsoft Corp', type: 'Stock', currency: 'USD' },
  { code: 'NVDA', name: 'NVIDIA Corp', type: 'Stock', currency: 'USD' },
  { code: 'AMZN', name: 'Amazon.com Inc', type: 'Stock', currency: 'USD' },
  { code: 'GOOGL', name: 'Alphabet Inc. (Google) Class A', type: 'Stock', currency: 'USD' },
  { code: 'META', name: 'Meta Platforms (Facebook)', type: 'Stock', currency: 'USD' },
  { code: 'TSLA', name: 'Tesla Inc', type: 'Stock', currency: 'USD' },
  { code: 'BRK.B', name: 'Berkshire Hathaway B', type: 'Stock', currency: 'USD' },
  { code: 'LLY', name: 'Eli Lilly and Company', type: 'Stock', currency: 'USD' },
  { code: 'AVGO', name: 'Broadcom Inc', type: 'Stock', currency: 'USD' },
  { code: 'V', name: 'Visa Inc', type: 'Stock', currency: 'USD' },
  { code: 'JPM', name: 'JPMorgan Chase & Co', type: 'Stock', currency: 'USD' },
  { code: 'WMT', name: 'Walmart Inc', type: 'Stock', currency: 'USD' },
  { code: 'XOM', name: 'Exxon Mobil Corp', type: 'Stock', currency: 'USD' },
  { code: 'UNH', name: 'UnitedHealth Group', type: 'Stock', currency: 'USD' },
  { code: 'MA', name: 'Mastercard Inc', type: 'Stock', currency: 'USD' },
  { code: 'PG', name: 'Procter & Gamble', type: 'Stock', currency: 'USD' },
  { code: 'JNJ', name: 'Johnson & Johnson', type: 'Stock', currency: 'USD' },
  { code: 'HD', name: 'Home Depot', type: 'Stock', currency: 'USD' },
  { code: 'MRK', name: 'Merck & Co', type: 'Stock', currency: 'USD' },
  { code: 'COST', name: 'Costco Wholesale', type: 'Stock', currency: 'USD' },
  { code: 'ABBV', name: 'AbbVie Inc', type: 'Stock', currency: 'USD' },
  { code: 'AMD', name: 'Advanced Micro Devices', type: 'Stock', currency: 'USD' },
  { code: 'NFLX', name: 'Netflix Inc', type: 'Stock', currency: 'USD' },
  { code: 'KO', name: 'Coca-Cola Company', type: 'Stock', currency: 'USD' },
  { code: 'PEP', name: 'PepsiCo Inc', type: 'Stock', currency: 'USD' },
  { code: 'DIS', name: 'Walt Disney Co', type: 'Stock', currency: 'USD' },
  { code: 'CSCO', name: 'Cisco Systems', type: 'Stock', currency: 'USD' },
  { code: 'MCD', name: 'McDonald\'s Corp', type: 'Stock', currency: 'USD' },
  { code: 'CRM', name: 'Salesforce Inc', type: 'Stock', currency: 'USD' },
  { code: 'INTC', name: 'Intel Corp', type: 'Stock', currency: 'USD' },
  { code: 'BA', name: 'Boeing Co', type: 'Stock', currency: 'USD' },
  { code: 'IBM', name: 'IBM', type: 'Stock', currency: 'USD' },
  { code: 'GS', name: 'Goldman Sachs', type: 'Stock', currency: 'USD' },
  { code: 'NKE', name: 'Nike Inc', type: 'Stock', currency: 'USD' },
  { code: 'SBUX', name: 'Starbucks Corp', type: 'Stock', currency: 'USD' },
  
  // --- ETFs / Mutual Funds ---
  { code: 'VOO', name: 'Vanguard S&P 500 ETF', type: 'ETF', currency: 'USD' },
  { code: 'VTI', name: 'Vanguard Total Stock Market ETF', type: 'ETF', currency: 'USD' },
  { code: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq-100)', type: 'ETF', currency: 'USD' },
  { code: 'AGG', name: 'iShares Core US Aggregate Bond', type: 'ETF', currency: 'USD' },
  { code: 'BND', name: 'Vanguard Total Bond Market', type: 'ETF', currency: 'USD' },
  { code: 'GLD', name: 'SPDR Gold Shares', type: 'ETF', currency: 'USD' },
  { code: 'VYM', name: 'Vanguard High Dividend Yield', type: 'ETF', currency: 'USD' },
  { code: 'VIG', name: 'Vanguard Dividend Appreciation', type: 'ETF', currency: 'USD' },
  { code: 'eMAXIS_All', name: 'eMAXIS Slim 全世界株式（オール・カントリー）', type: 'Mutual Fund', currency: 'JPY' },
  { code: 'eMAXIS_SP', name: 'eMAXIS Slim 米国株式（S&P500）', type: 'Mutual Fund', currency: 'JPY' },
  { code: 'eMAXIS_TOPIX', name: 'eMAXIS Slim 国内株式（TOPIX）', type: 'Mutual Fund', currency: 'JPY' },
  { code: 'eMAXIS_Nikkei', name: 'eMAXIS Slim 国内株式（日経平均）', type: 'Mutual Fund', currency: 'JPY' },
];